force-app/main/objects/HowTo__c/HowTo__c.object-meta.xml
<CustomObject>
    <description>Example object of the Ittes Base Package</description>
    <label>HowTo</label>
    <nameField>
        <displayFormat>HT{000}</displayFormat>
        <label>HowTo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HowTos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HowTo__c/fields/LogVeld__c.field-meta.xml
<CustomField>
    <fullName>LogVeld__c</fullName>
    <label>LogVeld</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/IIBP Howto/HowToHandler.cls
public with sharing class HowToHandler {
    private final IRepository oppRepo;

    public HowToHandler(Factory factory) {
        this.oppRepo = factory.RepoFactory.getOppRepo();
    }

    public override void afterInsert(List<SObject> insertedRecords, Map<Id, SObject> unused) {
        List<HowTo__c> insertedHowTos = (List<HowTo__c>) insertedRecords;
        this.setLog(insertedHowTos);
    }

    private void setLog(List<HowTo__c> insertedHowTos) {
        for (HowTo__c insertedHowTo : insertedHowTos) {
        
            insertedHowTo.LogVeld__c = system.now() + ' created.';
        }
        
    }
}