force-app/main/objects/HowTo__c/HowTo__c.object-meta.xml
<CustomObject>
    <description>Example object of the Ittes Base Package</description>
    <label>HowTo</label>
    <nameField>
        <displayFormat>HT{000}</displayFormat>
        <label>HowTo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HowTos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HowTo__c/fields/LogVeld__c.field-meta.xml
<CustomField>
    <fullName>LogVeld__c</fullName>
    <label>LogVeld</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/HowToChild__c/HowToChild__c.object-meta.xml
<CustomObject>
    <label>HowToChild</label>
    <nameField>
        <displayFormat>HTC{000}</displayFormat>
        <label>HowTo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HowToChildren</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/HowToChild__c/fields/HowTo__c.field-meta.xml
<CustomField>
    <fullName>HowTo__c</fullName>
    <label>HowTo</label>
    <referenceTo>HowTo__c</referenceTo>
    <relationshipLabel>HowToChildren</relationshipLabel>
    <relationshipName>HowToChildren</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HowToChild__c/fields/TekstVeld__c.field-meta.xml
<CustomField>
    <fullName>TekstVeld__c</fullName>
    <label>TekstVeld</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IIBP Howto/HowToTriggerhandler_Tests.cls
@isTest
public with sharing class HowToTriggerhandler_Tests {

    @isTest
    public static void realinsertTest(){
        //for coverage on the trigger itself.
        HowToTriggerhandler.bypassTrigger = true;
        HowTo__c ht = new HowTo__c();
        ht.TekstVeld__c = 'Tis nen uitleg gelijk een ander';

        insert ht;
        ht.LogVeld__c = 'blabla';
        update ht;
        delete ht;
        undelete ht;

        HowToTriggerhandler.bypassTrigger = false;
    }

    @IsTest
    static void beforeInsertHandler() {
        //IRepository repo = Factory.getFactory().withMocks.RepoFactory.getAccountRepo();

        HowTo__c ht = new HowTo__c();
        ht.Id = TestingUtils.generateId(HowTo__c.SObjectType);
        ht.TekstVeld__c = 'Tis nen uitleg gelijk een ander';

        

        Factory.getFactory()
        .withMocks.getHowToHandler()
        .beforeInsert(new List<SObject>{ ht }, new Map<Id, SObject>(new List<SObject>{ ht }));

        System.assert(ht.LogVeld__c.contains('Before Insert log'));
    }

    @IsTest
    static void afterInsertHandler() {
        HowTo__c ht = new HowTo__c();
        ht.Id = TestingUtils.generateId(HowTo__c.SObjectType);
        ht.TekstVeld__c = 'Tis nen uitleg gelijk een ander';

        Factory.getFactory()
        .withMocks.getHowToHandler()
        .afterInsert(new List<SObject>{ ht }, new Map<Id, SObject>(new List<SObject>{ ht }));

        HowToChild__c child = (HowToChild__c) DMLMock.Inserted.singleOrDefault;
        
        System.assertNotEquals(null, child, 'child should have been created!');
        System.assertEquals(ht.Id, child.HowTo__c);
    }
}