force-app/main/objects/HowTo__c/HowTo__c.object-meta.xml
<CustomObject>
    <description>Example object of the Ittes Base Package</description>
    <label>HowTo</label>
    <nameField>
        <displayFormat>HT{000}</displayFormat>
        <label>HowTo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HowTos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HowTo__c/fields/LogVeld__c.field-meta.xml
<CustomField>
    <fullName>LogVeld__c</fullName>
    <label>LogVeld</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/objects/HowToChild__c/HowToChild__c.object-meta.xml
<CustomObject>
    <label>HowToChild</label>
    <nameField>
        <displayFormat>HTC{000}</displayFormat>
        <label>HowTo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HowToChildren</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/objects/HowToChild__c/fields/HowTo__c.field-meta.xml
<CustomField>
    <fullName>HowTo__c</fullName>
    <label>HowTo</label>
    <referenceTo>HowTo__c</referenceTo>
    <relationshipLabel>HowToChildren</relationshipLabel>
    <relationshipName>HowToChildren</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HowToChild__c/fields/TekstVeld__c.field-meta.xml
<CustomField>
    <fullName>TekstVeld__c</fullName>
    <label>TekstVeld</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IIBP Howto/HowToMethods.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* HowToMethods
*
* Example class with functions and methods.
*   - Make sure methods accept lists or overload the methods to accomodate records or lists
*   - Methods should not have as few as possible database commits, you should work in records and lists 
*       and only commit to the db in the end. This reduces the testing complexity of different components
* 
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Nick Verschueren <Nick.Verschueren@ittesit.be>
* @version        0.0
* @created        10JAN2023
* @modified       10JAN2023
* @systemLayer    Utility 
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* v0.0            Nick.Verschueren@ittesit.be
* 10JAN2023       First Draft
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
public with sharing class HowToMethods {

    //How to insert a record;
    public static List<Account> AddTestAccounts(Integer Aantal){
        List<Account> accs = new List<Account>();
        for(Integer i = 0;i < Aantal;i++){
            Account acc = new Account();
            acc.Name = 'TestAccount ' + i;
            // acc.NumberofLocations__c = 1;

            accs.add(acc);
        }

        DML mock = DMLMock.getMock();
        mock.doInsert(accs);
        return accs;
    }

    //How to update a record
    public static void ChangeTestAccountName(Account acc){
        acc.Name = 'Jelle VV nv';


        DML mock = DMLMock.getMock();
        mock.doUpdate(acc);
    }

    //How to delete a record
    public static void deleteTestAccount(Account acc){
        DML mock = DMLMock.getMock();
        mock.doDelete(acc);
    }
    

    //method to add a logline to one record, will be overloaded to a methed that uses lists.
    public static HowTo__c addLog(HowTo__c record, String logLine){
        //create list, and call overloaded method, returns first listitem
        return addLog(new List<HowTo__c>{ record }, logLine)[0];
    }

    //method to add a logline to a list of records
    public static list<HowTo__c> addLog(list<HowTo__c> recordList, String logLine){
        //loop throuh list
        for (HowTo__c record : recordList) {
            if(record.LogVeld__c == null){
                record.LogVeld__c = Datetime.now() + ': ' + logLine;
            }
            else{
                record.LogVeld__c = record.LogVeld__c + '\n' + Datetime.now() + ': ' + logLine;
            }
            //add logline to Field
            
            system.debug(record.LogVeld__c);
        }
        //return updated list
        return recordList;
    }

    //method that creates
    public static void createChildRecord(List<HowTo__c> insertedHowTos, IRepository aggHowToRepo) {
        List<HowToChild__c> childrenToInsert = new List<HowToChild__c>();
        for (HowTo__c insertedHowTo : insertedHowTos) {
            childrenToInsert.add(
            new HowToChild__c(
                TekstVeld__c = 'Aangemaakt door trigger',
                HowTo__c = insertedHowTo.Id
            )
          );
        }
        aggHowToRepo.doInsert(childrenToInsert);
    }
}